using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HealthAssist.Handler
{
    public class SampleHandler : IHttpHandler
    {
        public bool IsReusable => false;

        public void ProcessRequest(HttpContext context)
        {
            context.Response.Write("<p>This was generated by the sample handler.</p>");
        }
    }
}